# -*- coding: utf-8 -*-
"""
Task : To have a look at the train and test datasets after they have been
       generated by ../dataset/input_data_generation.py
       
Utility Scripts Used :
    1. ../utils/data_background.py (Background info of the Train and Test sets)
"""

import pandas as pd
import sys
sys.path.append("../utils/")
import data_background as dbkg

# Loading the data
train = pd.read_csv("../dataset/train.csv")
test = pd.read_csv("../dataset/test.csv")

# Using the data_background.py utility script to check data
dbkg.train_test_compare(train, test)
dbkg.train_test_dist(train, test)